// Mock data для Foundry Observability UI
// Все строки на русском для UI-копий, английский для идентификаторов/кода

const STAGES = [
  { id: 'fetch',          label: 'fetch',      title: 'Fetch issue' },
  { id: 'context',        label: 'context',    title: 'Build context' },
  { id: 'agent_plan',     label: 'plan',       title: 'Agent plan' },
  { id: 'agent_implement',label: 'implement',  title: 'Agent implement' },
  { id: 'verify',         label: 'verify',     title: 'Verify' },
  { id: 'pr',             label: 'pr',         title: 'Open PR' },
];

// Набор иконок для tool-use событий (Lucide-like, монохром, 14px)
const ToolIcons = {
  Read:     'M4 4h10l4 4v12H4z M14 4v4h4',
  Edit:     'M4 20h4l10-10-4-4L4 16z M14 6l4 4',
  Write:    'M4 4h12v16H4z M8 8h4 M8 12h6 M8 16h4',
  Bash:     'M5 8l4 4-4 4 M12 16h6',
  Grep:     'M10 3a7 7 0 1 0 4.5 12.5L20 21 M10 3a7 7 0 0 1 7 7',
  Glob:     'M4 4h6v6H4z M14 4h6v6h-6z M4 14h6v6H4z M14 14h6v6h-6z',
  Task:     'M4 7h16 M4 12h10 M4 17h16',
  WebFetch: 'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18 M3 12h18 M12 3c3 3 3 15 0 18 M12 3c-3 3-3 15 0 18',
  Thinking: 'M12 3a6 6 0 0 0-4 10.5V17h8v-3.5A6 6 0 0 0 12 3z M10 20h4',
  Final:    'M5 13l4 4L19 7',
};

// Три задачи в разных состояниях
const TASKS = [
  {
    id: 'tsk_7f2a9c',
    repo: 'acme/foundry-web',
    issue_number: 412,
    issue_title: 'Add real-time agent action visibility to the dashboard',
    issue_body: 'Сейчас при прогоне пайплайна видно только financial-level события. Хочется видеть каждое действие агента: какой файл прочитан, какой инструмент вызван, что ответил LLM. Нужен live-поток в UI с возможностью раскрывать детали.',
    issue_author: 'mikhail',
    issue_labels: ['ui', 'observability', 'foundry-run'],
    status: 'RUNNING',
    current_stage: 'agent_implement',
    attempts: 1,
    branch: 'foundry/412-real-time-visibility',
    worktree: '.wt/412-real-time-visibility',
    pr_url: null,
    cost_usd: 0.42,
    tokens_in: 48200,
    tokens_out: 6120,
    started_at: 'сегодня, 14:02',
    duration_sec: 186,
    stages: {
      fetch: {
        status: 'done', duration: 2.1, cost: 0,
        agent: { name: 'gh cli', model: 'gh', provider: 'GitHub' },
        input:  { kind: 'kv', items: [['label', 'foundry-run'], ['repo', 'acme/foundry-web']] },
        output: { kind: 'kv', items: [['issue_number', '#412'], ['title', 'Add real-time agent action visibility…'], ['author', 'mikhail'], ['labels', 'ui, observability, foundry-run']] },
      },
      context: {
        status: 'done', duration: 0.8, cost: 0,
        agent: { name: 'foundry.context', model: 'stub', provider: 'local' },
        input:  { kind: 'kv', items: [['issue_number', '#412'], ['worktree', '.wt/412-real-time-visibility']] },
        output: { kind: 'files', label: 'Собрано 14 файлов, 3840 строк в контекст', items: [
          'src/api/main.py', 'src/foundry/agents/base.py', 'src/foundry/agents/claude_cli.py',
          'src/foundry/db/tasks.py', 'web/src/components/TaskRow.tsx', 'web/src/app.tsx',
          'docs/architecture/skeleton.md', '… +7 more'
        ]},
      },
      agent_plan: {
        status: 'done', duration: 48, cost: 0.09, tokens_in: 11200, tokens_out: 1840,
        agent: { name: 'claude code', model: 'claude-sonnet-4.5', provider: 'Anthropic' },
        input:  { kind: 'kv', items: [['model', 'claude-sonnet-4.5'], ['prompt_tokens', '11 200'], ['context_files', '14']] },
        output: { kind: 'text', label: 'Final plan', text: 'План из 4 шагов: (1) in-memory EventBus — отдельный модуль src/foundry/events/bus.py; (2) перевод run_cli_jsonl на asyncio.subprocess со стримингом событий; (3) SSE-эндпоинт /api/tasks/:id/events через StreamingResponse; (4) React-компонент EventStream в web/src/components/.' },
      },
      agent_implement: {
        status: 'running', duration: 134, cost: 0.33, tokens_in: 37000, tokens_out: 4280,
        agent: { name: 'claude code', model: 'claude-sonnet-4.5', provider: 'Anthropic' },
        input:  { kind: 'kv', items: [['model', 'claude-sonnet-4.5'], ['plan', 'из предыдущей стадии, 4 шага'], ['allowed_tools', 'Read, Edit, Write, Bash, Grep, Glob']] },
        output: { kind: 'pending', label: 'В процессе — результаты появятся после завершения' },
      },
      verify:          { status: 'pending' },
      pr:              { status: 'pending' },
    },
  },
  {
    id: 'tsk_3b1e4d',
    repo: 'acme/foundry-web',
    issue_number: 408,
    issue_title: 'Expose `/api/tasks/:id/events` SSE endpoint',
    issue_body: 'Нужен эндпоинт, который стримит tool-use события с ретрансляцией из in-memory pub/sub.',
    issue_author: 'andrey',
    issue_labels: ['api', 'foundry-run'],
    status: 'DONE',
    current_stage: 'done',
    attempts: 1,
    branch: 'foundry/408-sse-events',
    worktree: '.wt/408-sse-events',
    pr_url: 'https://github.com/acme/foundry-web/pull/408',
    pr_number: 421,
    cost_usd: 0.28,
    tokens_in: 31400,
    tokens_out: 4010,
    started_at: 'сегодня, 13:11',
    duration_sec: 245,
    stages: {
      fetch: { status: 'done', duration: 1.8, cost: 0,
        input: { kind: 'kv', items: [['label', 'foundry-run']] },
        output: { kind: 'kv', items: [['issue_number', '#408'], ['title', 'Expose `/api/tasks/:id/events` SSE endpoint']] },
      },
      context: { status: 'done', duration: 0.6, cost: 0,
        input: { kind: 'kv', items: [['issue_number', '#408']] },
        output: { kind: 'files', label: 'Собрано 8 файлов', items: ['src/api/main.py', 'src/api/stream.py', 'src/foundry/events/bus.py', '… +5'] },
      },
      agent_plan:      { status: 'done', duration: 32,  cost: 0.06,
        input: { kind: 'kv', items: [['model', 'claude-sonnet-4.5']] },
        output: { kind: 'text', label: 'Plan', text: 'Добавить StreamingResponse в FastAPI, подписываться на EventBus, сериализовать в SSE-формат.' },
      },
      agent_implement: { status: 'done', duration: 178, cost: 0.22,
        input: { kind: 'kv', items: [['model', 'claude-sonnet-4.5']] },
        output: { kind: 'files', label: 'Изменено 4 файла', items: ['src/api/stream.py (+38 new)', 'src/api/main.py (+12 −2)', 'tests/test_stream.py (+48 new)'] },
      },
      verify:          { status: 'done', duration: 12,  cost: 0,
        input: { kind: 'kv', items: [['cmd', 'pytest tests/ -q']] },
        output: { kind: 'text', label: 'stdout', text: '38 passed in 11.4s' },
      },
      pr:              { status: 'done', duration: 21,  cost: 0,
        input: { kind: 'kv', items: [['branch', 'foundry/408-sse-events']] },
        output: { kind: 'kv', items: [['pr_number', '#421'], ['url', 'github.com/acme/foundry-web/pull/421']] },
      },
    },
  },
  {
    id: 'tsk_9a4c21',
    repo: 'acme/foundry-cli',
    issue_number: 77,
    issue_title: 'Support `--stream-json` flag in `foundry run`',
    issue_body: 'Добавить флаг, чтобы CLI тоже рендерил tool-use события в stdout.',
    issue_author: 'mikhail',
    issue_labels: ['cli'],
    status: 'FAILED',
    current_stage: 'verify',
    attempts: 2,
    branch: 'foundry/77-stream-json-flag',
    worktree: '.wt/77-stream-json-flag',
    pr_url: null,
    cost_usd: 0.15,
    tokens_in: 18900,
    tokens_out: 2210,
    started_at: 'сегодня, 12:47',
    duration_sec: 412,
    error: {
      stage: 'verify',
      message: 'pytest exited with status 1',
      trace: [
        '  File "src/foundry/verify.py", line 82, in run_verify',
        '    raise VerifyFailed(result.stderr)',
        'foundry.verify.VerifyFailed:',
        '  FAILED tests/test_cli.py::test_stream_json_flag',
        '  AssertionError: expected 3 events, got 0',
        '    assert [].count() == 3',
      ],
    },
    stages: {
      fetch: { status: 'done', duration: 2.0,
        input:  { kind: 'kv', items: [['label', 'foundry-run'], ['repo', 'acme/foundry-cli']] },
        output: { kind: 'kv', items: [['issue_number', '#77'], ['title', 'Support `--stream-json` flag…']] },
      },
      context: { status: 'done', duration: 0.7,
        input:  { kind: 'kv', items: [['issue_number', '#77']] },
        output: { kind: 'files', label: 'Собрано 9 файлов', items: ['src/foundry/cli.py', 'tests/test_cli.py', 'src/foundry/run.py', '… +6 more'] },
      },
      agent_plan: { status: 'done', duration: 41, cost: 0.04,
        input:  { kind: 'kv', items: [['model', 'claude-sonnet-4.5']] },
        output: { kind: 'text', label: 'Plan', text: 'Добавить опцию Click --stream-json, пробрасывать флаг в run_cli_jsonl, тесты на stdout.' },
      },
      agent_implement: { status: 'done', duration: 312, cost: 0.11,
        input:  { kind: 'kv', items: [['model', 'claude-sonnet-4.5']] },
        output: { kind: 'files', label: 'Изменено 3 файла', items: ['src/foundry/cli.py (+22 −4)', 'src/foundry/run.py (+8 −1)', 'tests/test_cli.py (+34 new)'] },
      },
      verify: { status: 'failed', duration: 18,
        input:  { kind: 'kv', items: [['cmd', 'pytest tests/ -q']] },
        output: { kind: 'error', label: 'pytest exited with status 1', text: 'FAILED tests/test_cli.py::test_stream_json_flag' },
      },
      pr:              { status: 'skipped' },
    },
  },
  {
    id: 'tsk_1d8f0e',
    repo: 'acme/foundry-web',
    issue_number: 415,
    issue_title: 'Dark theme polish for `TaskRow` hover state',
    issue_body: '',
    issue_author: 'lena',
    issue_labels: ['design', 'ui'],
    status: 'PENDING',
    current_stage: 'fetch',
    attempts: 0,
    branch: null,
    worktree: null,
    pr_url: null,
    cost_usd: 0,
    tokens_in: 0,
    tokens_out: 0,
    started_at: '—',
    duration_sec: 0,
    stages: {
      fetch:           { status: 'pending' },
      context:         { status: 'pending' },
      agent_plan:      { status: 'pending' },
      agent_implement: { status: 'pending' },
      verify:          { status: 'pending' },
      pr:              { status: 'pending' },
    },
  },
  {
    id: 'tsk_5c6b2a',
    repo: 'acme/foundry-web',
    issue_number: 401,
    issue_title: 'Persist `logs_json` per-stage with timestamps',
    issue_body: '',
    issue_author: 'andrey',
    issue_labels: ['backend'],
    status: 'DONE',
    current_stage: 'done',
    attempts: 1,
    branch: 'foundry/401-logs-timestamps',
    pr_url: 'https://github.com/acme/foundry-web/pull/414',
    pr_number: 414,
    cost_usd: 0.19,
    tokens_in: 22100,
    tokens_out: 3020,
    started_at: 'сегодня, 11:02',
    duration_sec: 198,
    stages: {
      fetch:           { status: 'done', duration: 1.6 },
      context:         { status: 'done', duration: 0.5 },
      agent_plan:      { status: 'done', duration: 28,  cost: 0.05 },
      agent_implement: { status: 'done', duration: 142, cost: 0.14 },
      verify:          { status: 'done', duration: 10 },
      pr:              { status: 'done', duration: 16 },
    },
  },
  {
    id: 'tsk_2e7a18',
    repo: 'acme/foundry-docs',
    issue_number: 22,
    issue_title: 'Document the streaming JSONL event protocol',
    status: 'DONE',
    current_stage: 'done',
    attempts: 1,
    branch: 'foundry/22-stream-docs',
    pr_url: 'https://github.com/acme/foundry-docs/pull/28',
    pr_number: 28,
    cost_usd: 0.07,
    tokens_in: 8400,
    tokens_out: 1120,
    started_at: 'вчера, 18:40',
    duration_sec: 112,
    issue_author: 'mikhail',
    issue_labels: ['docs'],
    issue_body: '',
    stages: {
      fetch:           { status: 'done' },
      context:         { status: 'done' },
      agent_plan:      { status: 'done', cost: 0.02 },
      agent_implement: { status: 'done', cost: 0.05 },
      verify:          { status: 'done' },
      pr:              { status: 'done' },
    },
  },
];

// Помечу события привязкой к стадии (для фильтрации при клике на stage)
// Полный поток событий для активной задачи #412 (implement стадия)
// Каждое событие — tool_use, thinking, text или result.
const EVENTS_412 = [
  { ts: '14:02:18', kind: 'stage', stage: 'fetch', text: 'Fetched issue #412 from acme/foundry-web' },
  { ts: '14:02:20', kind: 'stage', stage: 'context', text: 'Collected 14 files into context window' },
  { ts: '14:02:21', kind: 'stage', stage: 'agent_plan', text: 'Plan agent started (claude-sonnet-4.5)' },
  { ts: '14:02:24', stage: 'agent_plan', kind: 'thinking', text: 'Нужно понять, как устроен текущий TaskRow и где добавить индикатор live-потока…' },
  { ts: '14:02:27', stage: 'agent_plan', kind: 'tool', tool: 'Read', detail: 'src/api/main.py', meta: '· 142 lines' },
  { ts: '14:02:28', stage: 'agent_plan', kind: 'tool', tool: 'Read', detail: 'src/foundry/agents/base.py', meta: '· 86 lines' },
  { ts: '14:02:30', stage: 'agent_plan', kind: 'tool', tool: 'Grep', detail: 'run_cli_jsonl', meta: '· 3 matches' },
  { ts: '14:02:32', stage: 'agent_plan', kind: 'tool', tool: 'Read', detail: 'src/foundry/agents/claude_cli.py', meta: '· 212 lines' },
  { ts: '14:02:38', stage: 'agent_plan', kind: 'thinking', text: 'Текущий run_cli_jsonl использует subprocess.run — нужно переписать на asyncio.subprocess и поднять pub/sub.' },
  { ts: '14:02:46', stage: 'agent_plan', kind: 'text', text: 'Готов план из 4 шагов: (1) in-memory EventBus, (2) async streaming из claude CLI, (3) SSE-эндпоинт, (4) React-компонент EventStream.' },
  { ts: '14:03:05', kind: 'stage', stage: 'agent_implement', text: 'Implement agent started' },
  { ts: '14:03:09', stage: 'agent_implement', kind: 'tool', tool: 'Read', detail: 'src/foundry/agents/base.py' },
  { ts: '14:03:12', stage: 'agent_implement', kind: 'tool', tool: 'Edit', detail: 'src/foundry/agents/base.py', meta: '+48 −12' },
  { ts: '14:03:20', stage: 'agent_implement', kind: 'tool', tool: 'Write', detail: 'src/foundry/events/bus.py', meta: '· new, 64 lines' },
  { ts: '14:03:24', stage: 'agent_implement', kind: 'tool', tool: 'Bash', detail: 'python -m pytest tests/test_bus.py -q', meta: '· 4 passed' },
  { ts: '14:03:30', stage: 'agent_implement', kind: 'tool', tool: 'Read', detail: 'src/api/main.py' },
  { ts: '14:03:36', stage: 'agent_implement', kind: 'tool', tool: 'Edit', detail: 'src/api/main.py', meta: '+22 −4' },
  { ts: '14:03:42', stage: 'agent_implement', kind: 'thinking', text: 'Теперь надо отдать поток через SSE. FastAPI умеет это через StreamingResponse.' },
  { ts: '14:03:50', stage: 'agent_implement', kind: 'tool', tool: 'Write', detail: 'src/api/stream.py', meta: '· new, 38 lines' },
  { ts: '14:03:55', stage: 'agent_implement', kind: 'tool', tool: 'Bash', detail: 'python -m pytest tests/ -q', meta: '· 38 passed' },
  { ts: '14:04:02', stage: 'agent_implement', kind: 'tool', tool: 'Grep', detail: 'TaskRow', meta: '· 2 matches' },
  { ts: '14:04:06', stage: 'agent_implement', kind: 'tool', tool: 'Read', detail: 'web/src/components/TaskRow.tsx' },
  { ts: '14:04:12', stage: 'agent_implement', kind: 'tool', tool: 'Edit', detail: 'web/src/components/TaskRow.tsx', meta: '+18 −2' },
  { ts: '14:04:18', stage: 'agent_implement', kind: 'tool', tool: 'Write', detail: 'web/src/components/EventStream.tsx', meta: '· new, 104 lines' },
  { ts: '14:04:28', stage: 'agent_implement', kind: 'tool', tool: 'Bash', detail: 'pnpm -C web test --run', meta: '· running…', live: true },
];

if (typeof window !== 'undefined') {
  Object.assign(window, { STAGES, ToolIcons, TASKS, EVENTS_412 });
}
